// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH7jcKwO0K_DtRd9Sn9SXg3IeHHDW1qgQ',
    appId: '1:743533051730:web:c58983c5d5b9feb94bc48b',
    messagingSenderId: '743533051730',
    projectId: 'uquts-1c23c',
    authDomain: 'uquts-1c23c.firebaseapp.com',
    storageBucket: 'uquts-1c23c.firebasestorage.app',
    measurementId: 'G-S57NJQTG3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtt2vOEea7LvAi7wNGoohwBGzmPW92z8Q',
    appId: '1:743533051730:android:511ddd05de4761b64bc48b',
    messagingSenderId: '743533051730',
    projectId: 'uquts-1c23c',
    storageBucket: 'uquts-1c23c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiJcWjOwaAIncLRodqE_QcjSbZqoM-XCY',
    appId: '1:743533051730:ios:41d02883995d8e0d4bc48b',
    messagingSenderId: '743533051730',
    projectId: 'uquts-1c23c',
    storageBucket: 'uquts-1c23c.firebasestorage.app',
    iosBundleId: 'com.example.uquts1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiJcWjOwaAIncLRodqE_QcjSbZqoM-XCY',
    appId: '1:743533051730:ios:41d02883995d8e0d4bc48b',
    messagingSenderId: '743533051730',
    projectId: 'uquts-1c23c',
    storageBucket: 'uquts-1c23c.firebasestorage.app',
    iosBundleId: 'com.example.uquts1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH7jcKwO0K_DtRd9Sn9SXg3IeHHDW1qgQ',
    appId: '1:743533051730:web:b11c498a22faa59b4bc48b',
    messagingSenderId: '743533051730',
    projectId: 'uquts-1c23c',
    authDomain: 'uquts-1c23c.firebaseapp.com',
    storageBucket: 'uquts-1c23c.firebasestorage.app',
    measurementId: 'G-86J7SJ38MV',
  );

}